### ISSUE TITLE
Lock acquisition needs to be first-come-first-served

### ISSUE THREAD

**Issue by ardijusufi** [nyu-adb-fall17-dyaj/RepCRec#10]
From the project requirements:

> If x is currently read-locked by T1 and T3 is waiting for a write lock on x and T2 subsequently requests a read lock on x, then T2 must wait for T3 either to be aborted or to complete its possession of x; that is, T2 cannot skip T3.

That means that `R(T2,x1)` (tick 5) in the following code should fail because `T3` is waiting for a write lock on `x1`, but with the current code that read succeeds:

```
begin(T1)
begin(T2)
begin(T3)
R(T1,x1)
W(T3,x1,5)
R(T2,x1)
end(T1)
end(T3)
end(T2)
```

**Comment by ardijusufi** [comment]
Also, after fixing this let's discuss and test what happens if instead we're reading/writing a replicated variable, such as follows:

```
begin(T1)
begin(T2)
begin(T3)
R(T1,x2)
W(T3,x2,5)
R(T2,x2)
end(T1)
end(T3)
end(T2)
```

**Comment by dy877-nyu** [comment]
In both cases, T2 needs to wait until T3 commits to read
