### ISSUE TITLE
Abort transaction when it can't commit its write at end

### ISSUE THREAD

**Issue by ardijusufi** [nyu-adb-fall17-dyaj/RepCRec#11]
At commit time, check if trx.wait_for is empty. If not, then abort it. I.e. T1 below should abort:

```
begin(T0)
begin(T1)
R(T0,x1)
W(T1,x1,4)
end(T1)
end(T0)
```

**Comment by dy877-nyu** [comment]
just check if trx is running or waiting

**Comment by ardijusufi** [comment]
So you fixed this by aborting a transaction that at commit time was on the waitlist:

```
    def end(self, trx):
        if trx in self.waitlist:
            self.abort(trx)
            return
```

https://github.com/nyu-adb-fall17-dyaj/RepCRec/blob/f8959aec2b008f3443c0fb1e7c75ddefbe57bf8e/src/transaction_manager.py#L170

It's equivalent to checking if `trx.wait_for` is empty at commit time. In other words, I think this issue is fixed now.
