### ISSUE TITLE
Committing aborted transactions

### ISSUE THREAD

**Issue by ardijusufi** [nyu-adb-fall17-dyaj/RepCRec#15]
Say we get the following input:
```
begin(T1)
begin(T2)
R(T1,x1)
W(T2,x1,1)
R(T2,x2)
W(T1,x2,4)
end(T1)
end(T2)
```
When we get `end(T1)`, deadlock detection will **abort** `T2` because it's younger. However, due to `end(T2)`, `T2` at the end will appear to have committed.

According to the test files the professor provided, when there's a deadlock, they won't provide `end(transaction i)` as input if `transaction i` gets aborted due to deadlock detection. However, just in case, do you think we should address this issue? (It's easy -- at the beginning of `transaction_manager.end(trx)`, just check if `trx` was aborted and if so, return).

**Comment by dy877-nyu** [comment]
I can add that.
The input is wrong though. When T2 waits to write x1, we will not receive another operation for T2.

**Comment by ardijusufi** [comment]
You're right, I mentioned that. I guess we're guaranteed that the input is formed properly so this wouldn't be an issue for the purpose of this project.
