### ISSUE TITLE
Never skip waitlisted transactions

### ISSUE THREAD

**Issue by ardijusufi** [nyu-adb-fall17-dyaj/RepCRec#16]
Look at this input:

```
begin(T1)
begin(T2)
R(T1,x1)
W(T1,x1,100)
W(T2,x1,200)
R(T2,x1)
R(T1,x1)
end(T1)
R(T2,x1)
end(T2)
```
What do you think should happen when we reach `end(T1)`? I think that the waitlisted transactions should be retried (in this case, they are 1) `W(T2,x1,200)` 2) `R(T2,x1)`. As a result, `R(T2,x1)` should return `200` (the uncommitted value of `T2`).

However, right now this returns the value committed by `T1`. I'll try to debug this further (I looked at `_waits_for_write` and how transactions are appended to `waitlist`). Let's discuss this in person.

**Comment by dy877-nyu** [comment]
When T2 waits to write x1, we will not receive another operation for T2.
